export const shareStyles = `
.spool-sharing-surface{position:fixed;inset:0;z-index:80;display:flex;align-items:center;justify-content:center;box-sizing:border-box;padding:22px;visibility:hidden;pointer-events:none;font:13px/1.5 var(--font-sans,"Instrument Sans Variable",system-ui);color:var(--color-text);transition:visibility 120ms}
.spool-sharing-surface[data-open=true]{visibility:visible;pointer-events:auto}
.spool-sharing-scrim{position:absolute;inset:0;border:0;background:color-mix(in srgb,var(--color-bg,#111) 55%,transparent);backdrop-filter:none;opacity:0;transition:opacity 120ms ease-out}
.spool-sharing-surface[data-open=true] .spool-sharing-scrim{opacity:1;transition-duration:120ms}
.spool-sharing-panel{position:relative;display:flex;flex-direction:column;width:410px;max-width:100%;max-height:100%;border:1px solid var(--color-border-raised);border-radius:10px;background:var(--color-raised);overflow:auto;opacity:0;transform:translateY(6px);transition:opacity 100ms ease-out,transform 180ms cubic-bezier(.23,1,.32,1)}
.spool-sharing-surface[data-open=true] .spool-sharing-panel{opacity:1;transform:none;transition:opacity 100ms ease-out,transform 180ms cubic-bezier(.23,1,.32,1)}
.spool-sharing-measure{flex-shrink:0}.spool-share-content.spool-share-unavailable{padding:22px}.spool-sharing-header{display:flex;align-items:center;justify-content:space-between;padding:22px;height:auto;border-bottom:1px solid var(--color-border-raised)}
.spool-sharing-header h1{font:500 18px/1.4 var(--font-sans,"Instrument Sans Variable",system-ui);margin:0}
.spool-sharing-header>div{display:flex;align-items:center;gap:12px}.spool-sharing-header span{display:none}.spool-sharing-header button{border:0;background:transparent;color:var(--color-muted);cursor:pointer}
.spool-share-content{padding:8px 22px 0;overflow:hidden;flex-shrink:0}.spool-share-content p,.spool-share-tray p{font-size:12px;line-height:1.6;margin:12px 0}.spool-share-between{display:flex;align-items:center;justify-content:space-between;gap:16px}.spool-share-muted{color:var(--color-muted)}.spool-share-mono,.spool-share-tray-title{font:11px/1.5 var(--font-mono,"Fragment Mono",monospace)}
.spool-share-content strong,.spool-share-tray strong{font-weight:500;font-size:14px}.spool-share-content button,.spool-share-tray button{cursor:pointer;transition:color 140ms cubic-bezier(.23,1,.32,1),background-color 140ms cubic-bezier(.23,1,.32,1),transform 140ms cubic-bezier(.23,1,.32,1)}
.spool-share-content button:disabled,.spool-share-tray button:disabled{opacity:.5;cursor:default}.spool-share-content :focus-visible,.spool-share-tray :focus-visible{outline:2px solid var(--color-thread);outline-offset:3px}
.spool-share-content input,.spool-share-content select{box-sizing:border-box;width:100%;background:var(--color-surface);border:1px solid var(--color-border-raised);border-radius:5px;padding:11px 12px;font:inherit;color:var(--color-text)}
.spool-share-access label{display:block;margin-bottom:10px}.spool-share-address{display:flex;gap:10px}.spool-share-address input{min-width:0}.spool-share-recipients{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0 10px}.spool-share-recipients>span{display:flex;align-items:center;gap:10px;background:var(--color-surface);border:1px solid var(--color-border-raised);border-radius:4px;padding:6px 8px;font:11px var(--font-mono,"Fragment Mono",monospace);overflow-wrap:anywhere}.spool-share-recipients button{border:0;background:transparent;color:var(--color-muted)}
.spool-share-primary{background:var(--color-thread);color:var(--color-on-thread,#fff);padding:9px 13px;border-radius:5px;border:0;font-size:12px;white-space:nowrap}.spool-share-primary:active{transform:scale(.98)}.spool-share-full{width:100%;margin-top:14px}.spool-share-text{background:transparent;border:0;color:var(--color-muted);font-size:11px;text-decoration:none}.spool-share-text:hover{color:var(--color-text)}
.spool-share-scope{width:100%;padding:13px 0;border:0;border-top:1px solid var(--color-border-raised);border-bottom:1px solid var(--color-border-raised);font:11px var(--font-mono,"Fragment Mono",monospace);color:var(--color-text);margin:18px 0 24px;background:transparent;text-align:left}.spool-share-link{font:11px var(--font-mono,"Fragment Mono",monospace)!important;margin:18px 0}.spool-share-footer{padding:16px 0;margin-top:22px;border-top:1px solid var(--color-border-raised);color:var(--color-muted);font-size:11px}
.spool-share-tray{position:fixed;right:24px;bottom:24px;z-index:70;box-sizing:border-box;width:356px;max-width:calc(100% - 48px);padding:18px;border:1px solid var(--color-border-raised);border-radius:9px;background:var(--color-raised);color:var(--color-text);font:12px/1.5 var(--font-sans,"Instrument Sans Variable",system-ui);animation:spool-share-arrive 180ms cubic-bezier(.23,1,.32,1)}.spool-share-tray-title{border-bottom:1px solid var(--color-border-raised);padding-bottom:16px;margin-bottom:16px}.spool-share-meter{height:3px;margin:18px 0 10px;background:var(--color-border-raised);overflow:hidden}.spool-share-meter>span{display:block;height:100%;background:var(--color-thread);transform-origin:left;transition:transform 300ms cubic-bezier(.23,1,.32,1)}
.spool-share-steps{display:flex;gap:22px;margin-top:23px;font:10px var(--font-mono,"Fragment Mono",monospace);color:var(--color-muted)}.spool-share-steps span{border-top:1px solid var(--color-border-raised);padding-top:8px;flex:1}.spool-share-steps [data-current=true]{color:var(--color-text);border-color:var(--color-thread)}.spool-share-error{color:var(--color-thread)}
@keyframes spool-share-arrive{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
.spool-sharing-surface[data-instant=true],.spool-sharing-surface[data-instant=true] *{transition:none!important}
@media(prefers-reduced-motion:reduce){.spool-sharing-surface,.spool-sharing-surface *,.spool-share-tray,.spool-share-tray *{animation:none!important;transition:none!important}}
`;
