#!/bin/bash
set -euo pipefail

# Regenerates Sources/SpoolKit/MarkPath.swift from SPOOL_MARK_PATH in
# ../src/brand.ts, which is the identity export and the only place the ribbon is
# drawn from. Swift cannot import TypeScript and a Swift target has no
# stylesheet to read, so the geometry is copied rather than referenced. Copying
# it by hand is how two marks drift apart, so this does the copy and the file it
# writes is committed: a build never depends on being able to run this.
#
#   ./scripts/mark.sh
#
# Run it when the mark changes in src/brand.ts, and commit what it writes.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
OUT="$ROOT/Sources/SpoolKit/MarkPath.swift"

PATH_DATA="$(node -e '
  const source = require("node:fs").readFileSync(process.argv[1], "utf8");
  const match = source.match(/export const SPOOL_MARK_PATH\s*=\s*\n?\s*"([^"]+)"/);
  if (match === null) throw new Error("SPOOL_MARK_PATH not found in " + process.argv[1]);
  process.stdout.write(match[1]);
' "$REPO/src/brand.ts")"

{
	printf '%s\n' '// Generated by scripts/mark.sh from ../src/brand.ts. Do not edit by hand.'
	printf '%s\n' '//'
	printf '%s\n' '// SPOOL_MARK_PATH and the viewBox it is drawn in, verbatim. Mark.swift turns'
	printf '%s\n' '// the string into a CGPath; this file exists only so the copy is mechanical.'
	printf '%s\n' ''
	printf '%s\n' 'import CoreGraphics'
	printf '%s\n' ''
	printf '%s\n' '/// The spool ribbon, in the identity'"'"'s own coordinates.'
	printf '%s\n' 'public let spoolMarkPathData ='
	printf '  "%s"\n' "$PATH_DATA"
	printf '%s\n' ''
	printf '%s\n' '/// The identity'"'"'s viewBox: "250 182 524 660". y grows downward, as in SVG.'
	printf '%s\n' 'public let spoolMarkViewBox = CGRect(x: 250, y: 182, width: 524, height: 660)'
} > "$OUT"

echo "wrote $OUT"
