#!/usr/bin/env bash
#
# A wizard: walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear: wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title": opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later. Nothing is stored anywhere until the last stage.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name": clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "...": a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "...": a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL: open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser, visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, visit it manually: $url"
}

# pause "msg": wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question": y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt": read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt": like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE: upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE: set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name, gh not ready; set it later"
}

# set_var NAME VALUE: set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish: clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Nothing captured here is written to a file. The certificate and its password
# are the keys to signing software as this company, and a .env holding them
# would outlive the reason it existed. They go from your clipboard to GitHub's
# secret store and nowhere else.
ENV_FILE="/dev/null"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERT_SELF="no"
KEY_SELF="no"

banner "Spool for macOS: signing and notarization"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools, and which repository these secrets will land on."
printf '\n'

cd "$REPO_DIR"

MISSING=""
for tool in gh security xcrun openssl; do
  command -v "$tool" > /dev/null 2>&1 || MISSING="$MISSING $tool"
done
if [[ -n "$MISSING" ]]; then
  warn "missing:$MISSING"
  say "Install those first. gh comes from Homebrew; the rest ship with macOS and"
  say "the Xcode Command Line Tools (xcode-select --install)."
  exit 1
fi
note "tools: gh, security, xcrun, openssl all present"

if ! gh auth status > /dev/null 2>&1; then
  warn "gh is not logged in. Run: gh auth login"
  exit 1
fi
note "gh: logged in"

REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2> /dev/null || echo "")"
if [[ -z "$REPO" ]]; then
  warn "this directory is not a GitHub repository gh can see: $REPO_DIR"
  exit 1
fi
printf '\n'
say "Secrets will be set on ${BOLD}${REPO}${RESET}."
if ! confirm "Is that the right repository?"; then
  say "Run this from a checkout of the repository you meant."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Who is allowed to create these"
say "Two artifacts are needed, and Apple gates them at different heights:"
printf '\n'
step "A Developer ID Application certificate. ${BOLD}Account Holder only${RESET}, and there"
say "  is exactly one of those on a team. A team may hold five certificates."
step "An App Store Connect API key. ${BOLD}Account Holder or Admin${RESET}, so an Admin can"
say "  make this one without troubling anybody."
printf '\n'
say "Your own role on the Apple Developer team decides how much of this you can"
say "do alone. Check it under Users and Access if you are not sure."
printf '\n'
say "  ${BOLD}1${RESET}  Signed in as the Account Holder, so you can do both"
say "  ${BOLD}2${RESET}  Signed in with your own Admin account, so the key is yours to make"
say "     and only the certificate needs the Account Holder"
say "  ${BOLD}3${RESET}  No access to that account, so both have to come from him"
printf '\n'

# Bounded, so a closed stdin ends the wizard instead of spinning on an empty
# answer forever.
ACCESS=""
ATTEMPTS=0
while [[ ! "$ACCESS" =~ ^[123]$ ]]; do
  if ((ATTEMPTS >= 3)); then
    warn "no answer after three tries, stopping. Nothing has been changed."
    exit 1
  fi
  ATTEMPTS=$((ATTEMPTS + 1))
  ask ACCESS "Which one are you? [1, 2 or 3]"
done

case "$ACCESS" in
  1) CERT_SELF="yes"; KEY_SELF="yes" ;;
  2) CERT_SELF="no"; KEY_SELF="yes" ;;
  3) CERT_SELF="no"; KEY_SELF="no" ;;
esac

printf '\n'
if [[ "$CERT_SELF" == "yes" ]]; then
  note "you can make both artifacts yourself in the stages that follow"
elif [[ "$KEY_SELF" == "yes" ]]; then
  note "the key is yours to make; the certificate needs three minutes of his time"
else
  note "both need his account; this wizard writes what to send him"
fi
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The Developer ID certificate"
say "This starts on your machine either way. A certificate signing request holds"
say "your ${BOLD}public${RESET} key and asks Apple to vouch for it. The private half stays"
say "here, and it is the half that actually signs the app."
printf '\n'

HAVE_P12="no"
if confirm "Do you already have a .p12 holding the certificate and its key?"; then
  HAVE_P12="yes"
fi

if [[ "$HAVE_P12" == "no" ]]; then
  # Made with openssl rather than through Keychain Access. Certificate Assistant
  # fails on some machines with "The specified item could not be found in the
  # keychain", and there is nothing to debug in a dialog. This produces the same
  # PKCS#10 request every time, and the key never enters a keychain at all until
  # the runner imports it.
  SIGNING_DIR="$HOME/.spool-signing"
  mkdir -p "$SIGNING_DIR"
  chmod 700 "$SIGNING_DIR"
  CSR_PATH="$SIGNING_DIR/request.certSigningRequest"
  KEY_PATH="$SIGNING_DIR/signing.key"

  if [[ -f "$KEY_PATH" ]]; then
    warn "there is already a signing key at $KEY_PATH"
    say "If you are part way through this, keep it: the certificate coming back"
    say "belongs to that key and to no other."
    if ! confirm "Reuse the existing key and request?"; then
      say "Move that folder aside and run this again."
      exit 1
    fi
  else
    ask CSR_EMAIL "Your email, for the request:"
    if [[ -z "$CSR_EMAIL" ]]; then
      warn "the request needs an email address."
      exit 1
    fi
    /usr/bin/openssl req -new -newkey rsa:2048 -nodes \
      -keyout "$KEY_PATH" \
      -out "$CSR_PATH" \
      -subj "/emailAddress=$CSR_EMAIL/CN=Spool signing" > /dev/null 2>&1
    chmod 600 "$KEY_PATH"
  fi

  if ! /usr/bin/openssl req -in "$CSR_PATH" -noout -verify > /dev/null 2>&1; then
    warn "the request did not come out valid. Nothing to do but try again."
    exit 1
  fi
  printf '  %s✓%s request written to %s\n' "$GREEN" "$RESET" "$CSR_PATH"
  note "the private key beside it never leaves this machine"
  printf '\n'
fi

if [[ "$HAVE_P12" == "yes" ]]; then
  note "drag the file into this terminal to paste its path"
  ask P12_PATH "Path to the .p12:"
  P12_PATH="${P12_PATH/#\~/$HOME}"
  P12_PATH="${P12_PATH%\'}"
  P12_PATH="${P12_PATH#\'}"
  P12_PATH="${P12_PATH//\\ / }"
  if [[ ! -f "$P12_PATH" ]]; then
    warn "no file at: $P12_PATH"
    exit 1
  fi
  ask_secret P12_PASSWORD "Password for the .p12:"
fi

if [[ "$HAVE_P12" == "no" ]]; then

if [[ "$CERT_SELF" == "yes" ]]; then
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Under Software choose Developer ID, then Developer ID Application, Continue."
  step "Upload the .certSigningRequest, Continue, then Download the .cer."
  pause "Done? Press Enter."
else
  say "Now the Account Holder turns that into a certificate. They never see"
  say "anything secret: a request carries a public key, and what comes back is"
  say "public too. So send the file any way you like."
  printf '\n'
  REQUEST="I need three minutes of the Apple Developer account to sign the Spool
Mac app. Only the Account Holder can issue this kind of certificate, which is
the whole reason I cannot do it myself.

Attached is a certificate signing request I generated here. Nothing in it is
secret: it carries my public key, and the certificate that comes back is public
as well. The private key stays on my machine and never goes anywhere, which is
why there is no password for you to send me and nothing here you have to guard.

  1. Open https://developer.apple.com/account/resources/certificates/add
  2. Under Software pick Developer ID, then Developer ID Application, Continue.
  3. Upload the file I attached, Continue, then Download.
  4. Send me back the .cer file it gives you. That is all of it.

The team can hold five of these, so this does not use up anything we cannot
replace, and it is a one-time favour.

Thank you."
  printf '%s\n' "$REQUEST"
  printf '\n'
  say "The file to attach:"
  printf '  %s%s%s\n' "$BOLD" "$CSR_PATH" "$RESET"
  printf '\n'
  if command -v pbcopy > /dev/null 2>&1; then
    if confirm "Copy that message to the clipboard?"; then
      printf '%s' "$REQUEST" | pbcopy
      note "copied"
    fi
  fi
  printf '\n'
  if ! confirm "Has the .cer come back yet?"; then
    say "Nothing has been changed. Re-run this when it lands, and keep the request"
    say "file until then, because a new one would need a new certificate."
    exit 0
  fi
fi

printf '\n'
note "drag the file into this terminal to paste its path"
ask CER_PATH "Path to the .cer Apple issued:"
# Dragging a file into Terminal pastes its path with spaces backslash-escaped,
# and some shells wrap it in quotes. Undo both before looking for the file.
CER_PATH="${CER_PATH/#\~/$HOME}"
CER_PATH="${CER_PATH%\'}"
CER_PATH="${CER_PATH#\'}"
CER_PATH="${CER_PATH//\\ / }"
if [[ ! -f "$CER_PATH" ]]; then
  warn "no file at: $CER_PATH"
  exit 1
fi

# Apple hands out DER. Pair it back with the key that asked for it, and the two
# together are the .p12 the runner wants. The password is generated rather than
# invented: it exists only to wrap the file on its way to GitHub, and nobody,
# including you, ever has to type it again.
P12_PATH="$SIGNING_DIR/certificate.p12"
P12_PASSWORD="$(/usr/bin/openssl rand -base64 24)"

if ! /usr/bin/openssl x509 -inform DER -in "$CER_PATH" -out "$SIGNING_DIR/certificate.pem" > /dev/null 2>&1; then
  # Some browsers save it already converted, so try the other encoding before
  # deciding the file is wrong.
  if ! /usr/bin/openssl x509 -in "$CER_PATH" -out "$SIGNING_DIR/certificate.pem" > /dev/null 2>&1; then
    warn "that file is not a certificate this can read."
    say "It should be the .cer the download button gave you."
    exit 1
  fi
fi

# Apple issues the certificate but not the authority above it, and a bundle
# holding only the leaf is not a valid identity to macOS: it cannot see the path
# from your certificate up to the Apple root it already trusts. So fetch the
# intermediate that signed this one and pack it in alongside. Which intermediate
# depends on the Sub-CA chosen when the certificate was created, so read it off
# the certificate rather than guessing.
LEAF_ISSUER="$(/usr/bin/openssl x509 -in "$SIGNING_DIR/certificate.pem" -noout -issuer | sed 's/^issuer= *//')"
INTERMEDIATE_PEM="$SIGNING_DIR/intermediate.pem"
INTERMEDIATE_FOUND="no"

for url in \
  "https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer" \
  "https://www.apple.com/certificateauthority/DeveloperIDCA.cer"; do
  if ! curl -fsS -o "$SIGNING_DIR/intermediate.cer" "$url" > /dev/null 2>&1; then
    continue
  fi
  if ! /usr/bin/openssl x509 -inform DER -in "$SIGNING_DIR/intermediate.cer" -out "$INTERMEDIATE_PEM" > /dev/null 2>&1; then
    continue
  fi
  subject="$(/usr/bin/openssl x509 -in "$INTERMEDIATE_PEM" -noout -subject | sed 's/^subject= *//')"
  if [[ "$subject" == "$LEAF_ISSUER" ]]; then
    INTERMEDIATE_FOUND="yes"
    break
  fi
done

if [[ "$INTERMEDIATE_FOUND" == "no" ]]; then
  warn "could not fetch the authority that issued this certificate."
  say "It says it was issued by:"
  say "  $LEAF_ISSUER"
  say "Neither of Apple's published Developer ID intermediates matches that, so"
  say "either you are offline or the certificate is not a Developer ID one."
  exit 1
fi
printf '  %s✓%s chain: %s\n' "$GREEN" "$RESET" "$LEAF_ISSUER"

if ! /usr/bin/openssl pkcs12 -export \
  -inkey "$KEY_PATH" \
  -in "$SIGNING_DIR/certificate.pem" \
  -certfile "$INTERMEDIATE_PEM" \
  -out "$P12_PATH" \
  -passout pass:"$P12_PASSWORD" > /dev/null 2>&1; then
  warn "the certificate and the key would not pair up."
  say "That happens when the .cer was issued for a different request than the"
  say "key in $SIGNING_DIR. If a second request was made, the certificate has to"
  say "come from that one."
  exit 1
fi
chmod 600 "$P12_PATH"
rm -f "$SIGNING_DIR/certificate.pem"
printf '  %s✓%s built %s\n' "$GREEN" "$RESET" "$P12_PATH"

fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Checking the certificate is the right one"
say "Importing it into a throwaway keychain, which is exactly what the release"
say "workflow does on the runner. If an identity comes back here, one comes back"
say "there."
printf '\n'

CHECK_DIR="$(mktemp -d)"
CHECK_KEYCHAIN="$CHECK_DIR/check.keychain-db"
CHECK_PASSWORD="$(openssl rand -base64 24)"

# A keychain that is not in the search list is not consulted when macOS decides
# whether an identity is valid: the certificate is found, and then reported as
# not valid, which reads exactly like a bad certificate and is not one. The
# runner puts its keychain in the list for the same reason, so this check has to
# as well or it would fail things the release would accept. Read the existing
# list one entry per line, so a home directory with a space in it survives.
SEARCH_LIST=()
while IFS= read -r line; do
  line="${line#*\"}"
  line="${line%\"*}"
  [[ -n "$line" ]] && SEARCH_LIST+=("$line")
done < <(security list-keychains -d user)

cleanup_check() {
  if ((${#SEARCH_LIST[@]})); then
    security list-keychains -d user -s "${SEARCH_LIST[@]}" > /dev/null 2>&1 || true
  fi
  security delete-keychain "$CHECK_KEYCHAIN" > /dev/null 2>&1 || true
  rm -rf "$CHECK_DIR"
}
trap cleanup_check EXIT

security create-keychain -p "$CHECK_PASSWORD" "$CHECK_KEYCHAIN" > /dev/null
security unlock-keychain -p "$CHECK_PASSWORD" "$CHECK_KEYCHAIN" > /dev/null
security list-keychains -d user -s "$CHECK_KEYCHAIN" "${SEARCH_LIST[@]}" > /dev/null

if ! security import "$P12_PATH" -k "$CHECK_KEYCHAIN" -P "$P12_PASSWORD" -T /usr/bin/codesign > /dev/null 2>&1; then
  warn "macOS refused to import that file. Usually the password is wrong, or the"
  warn "export was 'Certificate' rather than the certificate with its private key."
  exit 1
fi

IDENTITY="$(security find-identity -v -p codesigning "$CHECK_KEYCHAIN" | { grep "Developer ID Application" || true; } | sed -n 's/.*"\(.*\)".*/\1/p')"
if [[ -z "$IDENTITY" ]]; then
  warn "that .p12 imported, but it holds no valid Developer ID Application identity."
  say "Everything in it, including what macOS refuses to trust:"
  # Without -v, so a certificate that is present but untrusted still shows up
  # with the reason attached. -v would hide the very thing you need to read.
  security find-identity -p codesigning "$CHECK_KEYCHAIN" 2>&1 | sed 's/^/    /' || true
  printf '\n'
  say "An Apple Development or Apple Distribution certificate cannot sign a public"
  say "download; it has to be Developer ID Application. If the right name is there"
  say "but says NOT_TRUSTED, the certificate did not come from Apple."
  exit 1
fi
if [[ "$(printf '%s\n' "$IDENTITY" | grep -c .)" != "1" ]]; then
  warn "that .p12 holds more than one Developer ID Application identity:"
  printf '%s\n' "$IDENTITY"
  say "The workflow expects exactly one. Export a single certificate."
  exit 1
fi

printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$IDENTITY"
cleanup_check
trap - EXIT
printf '\n'
note "the workflow reads this name out of the certificate, so it is not a secret"
note "you have to keep in step by hand"
pause "Press Enter to continue."

MACOS_CERTIFICATE="$(base64 < "$P12_PATH" | tr -d '\n')"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The notarization key"
if [[ "$KEY_SELF" == "yes" ]]; then
  say "An App Store Connect API key is what lets CI hand builds to Apple without"
  say "anybody's Apple ID password living in a repository."
  printf '\n'
  open_url "https://appstoreconnect.apple.com/access/integrations/api"
  step "Users and Access > Integrations > App Store Connect API, Team Keys tab."
  step "Generate API Key. Name it 'Spool notarization', role Developer."
  step "Download the .p8. Apple allows that download exactly once."
  step "Note the Key ID on the row, and the Issuer ID shown above the list."
  printf '\n'

  # Generating keys needs an Admin, but switching the API on for the team at all
  # is Account Holder only, and it is off until somebody does it. An Admin
  # landing here first sees a greyed out Request Access button and no way
  # forward, which looks like a permissions bug and is a one-click favour.
  if ! confirm "Did that page let you generate a key?"; then
    printf '\n'
    say "Then the API has never been switched on for this team. Only the Account"
    say "Holder can do that, and it is one click. Nothing comes back to you: once"
    say "it is on, you make the key yourself."
    printf '\n'
    REQUEST="One more click on the Apple account, about a minute, and nothing to send me.

Go to https://appstoreconnect.apple.com/access/integrations/api and press
Request Access. That switches on the App Store Connect API for the team. Only
the Account Holder can do it, which is why it is you again.

Once it is on I can generate the key I need myself and you are done with this.

Thank you."
    printf '%s\n' "$REQUEST"
    printf '\n'
    if command -v pbcopy > /dev/null 2>&1; then
      if confirm "Copy that message to the clipboard?"; then
        printf '%s' "$REQUEST" | pbcopy
        note "copied"
      fi
    fi
    printf '\n'
    CERT_HOME="${SIGNING_DIR:-the folder it came from}"
    say "The certificate work is safe, it is in"
    say "  $CERT_HOME"
    say "Run this again once he has pressed the button."
    exit 0
  fi
  printf '\n'
else
  say "This one is a real private key, unlike the certificate request, so it does"
  say "not travel in a mail thread. Ask for it as a one-time link."
  printf '\n'
  REQUEST="One more thing from the same account, and this one takes about five minutes.

  1. Open https://appstoreconnect.apple.com/access/integrations/api
  2. Users and Access > Integrations > App Store Connect API, Team Keys tab.
  3. Generate API Key, name it 'Spool notarization', role Developer.
  4. Download the .p8. Apple allows that download exactly once, so do not
     close the page until it is saved.
  5. Note the Key ID on the row and the Issuer ID above the list.

The .p8 is an actual private key, so please send it as a one-time link rather
than as an attachment, using whatever one-time secret sharing you already use.
The Key ID and the Issuer ID are not secret and can come in the message.

Thank you."
  printf '%s\n' "$REQUEST"
  printf '\n'
  if command -v pbcopy > /dev/null 2>&1; then
    if confirm "Copy that message to the clipboard?"; then
      printf '%s' "$REQUEST" | pbcopy
      note "copied"
    fi
  fi
  printf '\n'
  if ! confirm "Has the key come back yet?"; then
    say "Nothing has been changed. The certificate work above is not lost: it is"
    say "in your keychain and the .p12 is on disk. Re-run this when the key lands."
    exit 0
  fi
  printf '\n'
fi

note "drag the file into this terminal to paste its path"
ask P8_PATH "Path to the .p8:"
P8_PATH="${P8_PATH/#\~/$HOME}"
P8_PATH="${P8_PATH%\'}"
P8_PATH="${P8_PATH#\'}"
P8_PATH="${P8_PATH//\\ / }"
if [[ ! -f "$P8_PATH" ]]; then
  warn "no file at: $P8_PATH"
  exit 1
fi
ask NOTARY_KEY_ID "Key ID:"
ask NOTARY_ISSUER_ID "Issuer ID:"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Checking the key can actually talk to Apple"
say "Asking Apple for this team's notarization history. It returns nothing on a"
say "team that has never notarized anything, which is fine. What matters is that"
say "Apple answers at all, because that means the three values agree."
printf '\n'

if xcrun notarytool history \
  --key "$P8_PATH" \
  --key-id "$NOTARY_KEY_ID" \
  --issuer "$NOTARY_ISSUER_ID" > /dev/null 2>&1; then
  printf '  %s✓%s Apple accepted the key\n' "$GREEN" "$RESET"
else
  warn "Apple refused those credentials. Its own words:"
  printf '\n'
  xcrun notarytool history --key "$P8_PATH" --key-id "$NOTARY_KEY_ID" --issuer "$NOTARY_ISSUER_ID" 2>&1 | sed 's/^/    /' || true
  printf '\n'
  say "Usually one of: the Key ID and Issuer ID belong to different keys, the .p8"
  say "is not the one that matches this Key ID, or the key's role is too narrow."
  say "If you suspect the role, generate a fresh key with the App Manager role."
  exit 1
fi

NOTARY_KEY="$(base64 < "$P8_PATH" | tr -d '\n')"
printf '\n'
pause "Press Enter to install these on $REPO."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Installing the five secrets"
say "Everything above has been verified, so these go to $REPO now."
printf '\n'

set_secret MACOS_CERTIFICATE "$MACOS_CERTIFICATE"
set_secret MACOS_CERTIFICATE_PASSWORD "$P12_PASSWORD"
set_secret NOTARY_KEY "$NOTARY_KEY"
set_secret NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_secret NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"

printf '\n'
say "That is the whole setup. Nothing else here cuts a release: spool has one"
say "version number and changesets picks it. Merge the release PR that publish.yml"
say "keeps open, and the tag it cuts builds a notarized dmg onto the release page"
say "on its own. See docs/releases.md."
printf '\n'
warn "Keep the .p8 somewhere safe, or in the bin. GitHub will not show it again,"
warn "and Apple will not re-issue it at all. The certificate is replaceable: the"
warn "Account Holder can sign another request, and the team may hold five."
printf '\n'

if confirm "Delete the files this leaves on disk?"; then
  rm -f "$P12_PATH" "$P8_PATH"
  if [[ "$HAVE_P12" == "no" && -n "${SIGNING_DIR:-}" ]]; then
    # The private key too. It is inside the .p12 that GitHub now holds, and a
    # signing key sitting in a home directory is worth nothing to you and
    # something to somebody else.
    rm -f "$SIGNING_DIR/signing.key" "$SIGNING_DIR/request.certSigningRequest" \
      "$SIGNING_DIR/certificate.pem" "$SIGNING_DIR/certificate.p12"
    rmdir "$SIGNING_DIR" 2> /dev/null || true
    note "deleted, $SIGNING_DIR included. They live in GitHub's secret store now."
  else
    note "deleted. They live in GitHub's secret store now."
  fi
fi

finish
