// Builds everything the React frame variant needs, mirroring the decided serve model:
//   - vendor React ESM (react / jsx-runtime / react-dom-client) → public/vendor/
//     ("React ships pinned inside spool", #16 — one copy served, evaluated per realm)
//   - each screen component compiled to a standalone ESM module → public/react-screens/
//     ("frames compiled daemon-side", #12 — esbuild as a library, externals via import map)
//   - Tailwind v4 compiled over the screen sources → src/generated/frames-css.ts
//     ("finished CSS injected into the assembled document", #15 — inlined per srcdoc)
//
// Run: pnpm build:frames   (part of pnpm build)

import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const screensDir = join(root, "src", "screens-react");
const generatedDir = join(root, "src", "generated");
mkdirSync(generatedDir, { recursive: true });

// --- vendor react ------------------------------------------------------------
// One bundle for react + react-dom/client + jsx-runtime, all three import-map
// specifiers pointing at the same URL: single React instance by construction,
// one fetch, evaluated once per frame realm — the pinned-serve model (#16).
// React's CJS entries hide named exports behind conditional re-exports esbuild
// can't lift statically, so enumerate the real exports in node and emit a facade.

const SPECIFIERS = ["react", "react-dom/client", "react/jsx-runtime"];
{
	const seen = new Set<string>(["default"]);
	const lines: string[] = [];
	for (const [i, spec] of SPECIFIERS.entries()) {
		const mod = (await import(spec)) as Record<string, unknown>;
		const resolved = fileURLToPath(import.meta.resolve(spec));
		lines.push(`import m${i} from ${JSON.stringify(resolved)};`);
		if (i === 0) lines.push("export default m0;");
		for (const n of Object.keys(mod)) {
			if (seen.has(n) || !/^[A-Za-z_$][\w$]*$/.test(n)) continue;
			seen.add(n);
			lines.push(`export const ${n} = m${i}[${JSON.stringify(n)}];`);
		}
	}
	const facadePath = join(generatedDir, "vendor-react.entry.js");
	writeFileSync(facadePath, lines.join("\n"));
	await build({
		entryPoints: [facadePath],
		bundle: true,
		format: "esm",
		platform: "browser",
		minify: true,
		define: { "process.env.NODE_ENV": '"production"' },
		outfile: join(root, "public", "vendor", "react-bundle.js"),
		absWorkingDir: root,
		logLevel: "silent",
	});
}

// --- screens -----------------------------------------------------------------

const screenFiles = readdirSync(screensDir).filter((f) => f.endsWith(".tsx"));
await build({
	entryPoints: screenFiles.map((f) => join(screensDir, f)),
	bundle: true,
	format: "esm",
	platform: "browser",
	jsx: "automatic",
	external: ["react", "react/jsx-runtime", "react-dom/client"],
	outdir: join(root, "public", "react-screens"),
	absWorkingDir: root,
	logLevel: "silent",
});

// --- tailwind ----------------------------------------------------------------

const cssOut = join(generatedDir, "frames.tw.css");
execFileSync("pnpm", ["exec", "tailwindcss", "-i", join(screensDir, "frames.css"), "-o", cssOut, "--minify"], {
	cwd: root,
	stdio: ["ignore", "ignore", "inherit"],
});
const css = readFileSync(cssOut, "utf8");
writeFileSync(
	join(generatedDir, "frames-css.ts"),
	`// Generated by scripts/build-frames.ts — do not edit.\nexport const framesCss: string = ${JSON.stringify(css)};\nexport const framesCssBytes = ${css.length};\n`,
);

const sizes = screenFiles.map((f) => {
	const out = readFileSync(join(root, "public", "react-screens", f.replace(".tsx", ".js")), "utf8");
	return `${f.replace(".tsx", "")} ${(out.length / 1024).toFixed(1)}KB`;
});
const vendorTotal = readFileSync(join(root, "public", "vendor", "react-bundle.js"), "utf8").length;

console.log(`vendor react esm: ${(vendorTotal / 1024).toFixed(0)}KB (one bundle, single instance)`);
console.log(`screens: ${sizes.join(" · ")}`);
console.log(`tailwind css: ${(css.length / 1024).toFixed(1)}KB minified (inlined per frame document)`);
